Name: Arpit Hasmukhbhai Patel
Student ID: A20424085
Course Number : CS512
Semester : 1st


# Assignment 0

Question A

Q.A-1

In [1]:
print("2A-B")
import numpy as np
A= np.array([[1],[2],[3]])
B= np.array([[4],[5],[6]])
ans = np.subtract(2*A,B)
print(ans)

2A-B
[[-2]
 [-1]
 [ 0]]


Q.A-2

In [4]:
print("||A||")
n= np.linalg.norm(A)
print(n)

||A||
3.7416573867739413


In [7]:
print ("angle to positive x axis ")
x =np.degrees(np.arccos(A[0]/n))
print (x)

angle to positive x axis 
[74.49864043]


Q.A-3

In [9]:
print ("unit vector")
c= A/n
print(c)

unit vector
[[0.26726124]
 [0.53452248]
 [0.80178373]]


Q.A-4

In [10]:
x1=(A[0]/n)
y =(A[1]/n)
z =(A[2]/n)
print("the direction of cosine of A is %f, %f, %f"%(x1,y,z))

the direction of cosine of A is 0.267261, 0.534522, 0.801784


Q.A-5

In [11]:
print("matrix multiplicaton")
m1= A[0]*B[0] + A[1]*B[1]+A[2]*B[2]
print(m1)

matrix multiplicaton
[32]


Q.A-6

In [13]:
print("angle between a and b")
print(np.degrees(np.arccos(m1/n/np.linalg.norm(B))))

angle between a and b
[12.93315449]


Q.A-7

In [ ]:
#Suppose new vector (x,y,z)
#For perpendicular vector multiplication between A and new vector is Zero
#So x+2y+3Z=0
#There are many solution for this one of them is x=1, y=-2, z=1

Q.A-8

In [16]:
print("Cross product")
print("A X B")
c1 = np.array([[B[2]*A[1]-A[2]*B[1]],[A[2]*B[0]-B[2]*A[0]],[B[1]*A[0]-B[0]*A[1]]])
print(c1)

Cross product
A X B
[[[-3]]

 [[ 6]]

 [[-3]]]


In [17]:
print("Cross product")
print("B X A")
c2 = np.array([[B[1]*A[2]-B[2]*A[1]],[B[2]*A[0]-B[0]*A[2]],[B[0]*A[1]-B[1]*A[0]]])
print(c2)

Cross product
B X A
[[[ 3]]

 [[-6]]

 [[ 3]]]


Q.A-9

In [18]:
print("vector which is perpendicular to both A and B")
print(c1)

vector which is perpendicular to both A and B
[[[-3]]

 [[ 6]]

 [[-3]]]


Q.A-10

In [20]:
lin= int(np.linalg.det(A))
if(lin==0):
    print("A and B is linear dependent")
else:
    print("A and B is linear independent")

A and B is linear independent


Q.A-11

In [21]:
h = np.transpose(A)
print(np.dot(h,B))

[[32]]


# Question B

Q.B-1

In [1]:
import numpy as np
A = np.array([[1,2,3],[4,-2,3],[0,5,-1]])
B = np.array([[1,2,1],[2,1,-4],[3,-2,1]])
C = np.array([[1,2,3],[4,5,6],[-1,1,3]])

print (np.subtract(2*A,B))

[[ 1  2  5]
 [ 6 -5 10]
 [-3 12 -3]]


Q.B-2

In [6]:
d1=np.dot(A,B)
print(d1)
d2=np.dot(B,A)
print(d2)

[[ 14  -2  -4]
 [  9   0  15]
 [  7   7 -21]]
[[  9   3   8]
 [  6 -18  13]
 [ -5  15   2]]


Q.B-3

In [7]:
print("AB transpose")
print(np.transpose(np.dot(A,B)))
print("B transpose.A transpose")
print(np.dot(np.transpose(B),np.transpose(A)))

AB transpose
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]
B transpose.A transpose
[[ 14   9   7]
 [ -2   0   7]
 [ -4  15 -21]]


Q.B-4

In [10]:
print("determinant")
print(np.linalg.det(A))
print(np.linalg.det(C))

determinant
54.999999999999964
7.494005416219837e-16


Q.B-5

In [ ]:
#for matrix A
#sum(A[0]*A[1]) not zero
#sum(A[1]*A[2]) not zero
#sum(A[2]*A[0]) not zero
#so A does not have orthogonal set

#for Matrix B
#sum(B[0]*B[1]) zero
#sum(B[1]*B[2]) zero
#sum(B[2]*B[0]) zero
#SO B is orthogonal

#for matrix C
#sum(C[0]*C[1]) not zero
#sum(C[1]*C[2]) not zero
#sum(C[2]*C[0]) not zero
#so C does not have orthogonal set

Q.B-6

In [11]:
print("inverse")
print(np.linalg.inv(A))
print(np.linalg.inv(B))


inverse
[[-0.23636364  0.30909091  0.21818182]
 [ 0.07272727 -0.01818182  0.16363636]
 [ 0.36363636 -0.09090909 -0.18181818]]
[[ 0.16666667  0.0952381   0.21428571]
 [ 0.33333333  0.04761905 -0.14285714]
 [ 0.16666667 -0.19047619  0.07142857]]


# Question C

Q.C-1

In [12]:
import numpy as np
A = np.array([[1,2],[3,2]])
B = np.array([[2,-2],[-2,5]])
w,v = np.linalg.eigvals(A)
print("eigan value")
print(w)
print(v)

r,t = np.linalg.eig(A)
print("eigan vectors")
print(r)
print(t)

eigan value
-1.0
4.0
eigan vectors
[-1.  4.]
[[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]


Q.C-2

In [18]:
V = np.array([[1,1],[1.5,1]])
N = np.dot(np.linalg.inv(V),A,V)
print(N)


[[ 4.0000000e+00  4.4408921e-16]
 [-3.0000000e+00  2.0000000e+00]]


Q.C-3

In [13]:
print("dot product of eiganvectors of A")
z=np.dot(r,t)
print(z)

dot product of eiganvectors of A
[ 3.53553391 -2.77350098]


Q.C-4

In [15]:
d,f = np.linalg.eig(B)
print("eiganvectors of B")
print(d)
print(f)
print("dot")
print(np.dot(d,f))

eiganvectors of B
[1. 6.]
[[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]
dot
[-3.57770876 -4.91934955]
